### ISSUE TITLE
remove untared tif files at the end

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/i.landsat#16]
Once import is done, list of .tif files should be removed

**Comment by ninsbl** [comment]
Are you aware of GDALs virtual file systems:
https://gdal.org/user/virtual_file_systems.html

Might be an option instead of uncompressing and deleting afterwards, esp. if not r.external is used.

Python can also read the metadata file directly from the tar.gz:
https://docs.python.org/3/library/tarfile.html (getmember(), extract())

Just for consideration...

**Comment by veroandreo** [comment]
mhmm, yes... Now, I remove all tif files here https://github.com/veroandreo/i.landsat/commit/320e61b82ddfc3659a379134eede6863c60becba, but maybe the whole thing requires a different approach. How would you address your suggestions? :) I'm willing to keep learning and improve the modules

**Comment by ninsbl** [comment]
Your solution is just fine, and I do not know how different usage of virtual file systems would be in terms of storage or performace... So, no need to spend much time on it.

My thoulgs would have been to do, instead of this:
https://github.com/veroandreo/i.landsat/blob/320e61b82ddfc3659a379134eede6863c60becba/i.landsat.import/i.landsat.import.py#L115-L119

Something like:
```
import tarfile

# (...)
    tifs = []
    for scene in scenes_to_untar:
        with tarfile.open(scene) as tar:
            tifs = tifs + ["/vsitar/{}/{}".format(scene, filename for filename in scene.getnames() if filename.endswith(".TIF")]
```

That should give you a list of paths ot TIFs inside the .tar.gz that r.import or r.in.gdal (and I think also r.external) should be able to read (have not tested this though), comparable to what you get with untared_tifs now....

**Comment by veroandreo** [comment]
Thanks @ninsbl !!
